repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.18
    hooks:
      - id: flake8
